//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session1_03_Perepelkin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session2_03_PerepelkinEntities : DbContext
    {
        public Session2_03_PerepelkinEntities()
            : base("name=Session2_03_PerepelkinEntities")
        {
        }

        private static Session2_03_PerepelkinEntities _context = new Session2_03_PerepelkinEntities();

        public static Session2_03_PerepelkinEntities GetContext()
        {
            if (_context == null)
                _context = new Session2_03_PerepelkinEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LastLogin> LastLogin { get; set; }
        public virtual DbSet<SessionTime> SessionTime { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
