//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session1_03_Perepelkin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session1_03_PerepelkinEntities1 : DbContext
    {
        public Session1_03_PerepelkinEntities1()
            : base("name=Session1_03_PerepelkinEntities1")
        {
        }

        private static Session1_03_PerepelkinEntities1 _context;

        public static Session1_03_PerepelkinEntities1 GetContext()
        {
            if (_context == null)
                _context = new Session1_03_PerepelkinEntities1();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}
